environment: dev # or prod.

logger:
  file_name: wrapto.log
  log_level: info
  targets:
    - console
    - file
  max_size: 100
  max_backups: 10
  compress: true

pactus:
  wallet_path: /path/to/wallet
  lock_address: pc1zgp0x33hehvczq6dggs04gywfqpzl9fea5039gh
  rpc_url: https://rpc.pactus.example.com

polygon:
  contract_address: 0x2f77E0afAEE06970Bf860B8267b5aFECFFF6F216
  rpc_url: https://rpc.polygon.example.com

database:
  db_name: wrapto
  connection_timeout_in_ms: 5000
  query_timeout_in_ms: 3000

http:
  port: ":8080"