environment: dev # or prod.

logger:
  file_name: wrapto.log
  log_level: info
  targets:
    - console
    - file
  max_size: 100
  max_backups: 10
  compress: true

pactus:
  wallet_path: ./wallet
  lock_address: pc1zqyxjatqfhaj3arc727alwl4sa3z8lv2m730eh2
  wallet_address: pc1zqyxjatqfhaj3arc727alwl4sa3z8lv2m730eh2
  rpc_url: bootstrap1.pactus.org:50051

#! NEW EVM.
polygon:
  contract_address: 0x2f77E0afAEE06970Bf860B8267b5aFECFFF6F216
  rpc_url: https://polygon.drpc.org
  chain_id: 137 # polygon mainnet.

bsc:
  contract_address: 0x10004a9A742ec135c686C9aCed00FA3C93D66866
  rpc_url: https://bsc.drpc.org
  chain_id: 56 # bsc mainnet.

base:
  contract_address: 0x0000000000000000000000000000000000000000
  rpc_url: https://base.drpc.org
  chain_id: 8453 # base mainnet.

database:
  db_name: wrapto
  connection_timeout_in_ms: 5000
  query_timeout_in_ms: 3000

http:
  port: ":3000"
